name: Sync Staging To Development
run-name: Deploy ${{ github.event.inputs.branch_or_tag }} to ${{ github.event.inputs.apps }} ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      apps:
        description: 'Apps to sync'
        required: true
        default: cp
        type: choice
        options:
          - cp
          - oms

      from_environment:
        description: 'From environment'
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

      to_environment:
        description: 'To environment'
        required: true
        default: development
        type: choice
        options:
          - staging
          - development
