name: Sync Environments
run-name: Sync ${{ github.event.inputs.app }} from ${{ github.event.inputs.from_environment }} to ${{ github.event.inputs.to_environment}}

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App to sync'
        required: true
        default: cp
        type: choice
        options:
          - cp
          - oms

      from_environment:
        description: 'From environment'
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

      to_environment:
        description: 'To environment'
        required: true
        default: development
        type: choice
        options:
          - staging
          - development

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      PRODUCTION_RDS_SYNCER_PASSWORD: ${{ secrets.PRODUCTION_RDS_SYNCER_PASSWORD }}
      STAGING_RDS_ROOT_PASSWORD: ${{ secrets.STAGING_RDS_ROOT_PASSWORD }}

    steps:
      - name: Job Arguments
        run: |
          echo "App to sync: ${{ github.event.inputs.app }}"
          echo "From environment: ${{ github.event.inputs.from_environment }}"
          echo "To environment: ${{ github.event.inputs.to_environment }}"

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GH_BOT_SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: yarn install

      - name: Run sync
        run: |
          yarn sync config/${{ github.event.inputs.app }}-${{ github.event.inputs.from_environment }}-to-${{ github.event.inputs.to_environment }}.config.ts
